---
title: 'Thesis -- will need a more descriptive title!'
subtitle: "Master's Thesis"
author: 'Stefano Mezzini'
date: 'April 2023'
bibliography: 'masters-refs.bib'
# csl: unsure.csl
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{indentfirst} # add indent to first line of each paragraph
    # - \usepackage{gensymb}
    # - \usepackage{geometry} \geometry{margin=1in, lmargin=1.5in}
    # - \pagenumbering{gobble}
    # - \usepackage{float}
    # - \usepackage{afterpage}
    # - \usepackage{ragged2e}
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: true
    toc: true
    fig_caption: true
---

<!--

refer to the style guideline at https://github.com/jepa/ubcdown

add:
- headers
- references
- what I can apply from classes
-->

\newpage

# Introduction

- spend time reading papers initially to do a review, get a review paper out of it
- make predictions/hypotheses for project
- what influences stochasticity: what is it and what is affecting it
- very little testing has been done on effects of stochasticity

## Importance and recognition of Traditional Indigenous Knowledge

The ancestral and traditional Knowledge of Indigenous and colonized Peoples is often dismissed, ignored, and contradicted by Western institutions. The development of Western science is often assumed to clash with the sacred Knowledge many colonized People hold. Western science is also often viewed as more objective, methodical, and unbiased than traditional Knowledge, and as such it is believed by Western institutions to be superior to Indigenous Knowledge. However, it is common for Western institutions to (reluctantly) reach similar, if not identical, conclusions as those held by Indigenous people [@ref]. The refusal to recognize traditional Knowledge and cooperate with non-Western institutions often results in a loss of time, resources, and funds to the Western institutions and severe damage to the Land the institution operated on, as well as to the people who's ancestors inhabited the region for millennia. The development of Western science at the exclusion of Indigenous Peoples perpetuates colonialism and brings harm all parties involved. <!-- *damage to generations to come* -->

The concept of *two-eye seeing* [@ref] refers to an approach to knowledge and growth that braids Indigenous Knowledge and science together with Western science. Since Traditional Indigenous Knowledge tends to be qualitative, while biological sciences tend to be quantitative, connecting the two is not always simple. One possibility, however, is to use Traditional Knowledge to create well-informed Bayesian priors [@ref]. The validity of the priors can be ensured using prior predictive modeling to select priors that align with the Traditional Knowledge. This practice is not new [@girondot_bayesian_2015; @belisle_local_2018], but it is rarely used, despite it aligning well with the philosophy of Bayesian statistics.

- Inform priors and simulation distributions using Indigenous Traditional Knowledge:
    - A Bayesian framework with Indigenous Knowledge-informed priors [@girondot_bayesian_2015]
    - *Local knowledge in ecological modeling* [@belisle_local_2018]
    - https://focus.science.ubc.ca/stats-660805dd930a


- *A-spatial-overview-of-the-global-importance-of-Indigenous-lands-for-conservation*
- *Native knowledge for native ecosystems*
- *Searching for synergy integrating traditional and scientific ecological knowledge in environmental science education*
- *The Role of Indigenous Burning in Land Management*
- calls to action for scientists: @wong_towards_2020
- weaving TIK and Western knowledge: @tengo_weaving_2017
- *Weaving Indigenous knowledge systems and Western sciences in terrestrial research, monitoring and management in Canada: A protocol for a systematic map* [@henri_weaving_2021]
- *Indigenizing the North American Model of Wildlife Conservation* [@hessami_indigenizing_2021]
- fish conservation, Indigenous perspectives [@bowles_threepronged_2021]
- Vertebrate biodiversity in Indigenous-managed lands in Australia, Brazil, and Canada is equal to or greater biodiversity in protected areas [@schuster_vertebrate_2019]

## Time scale of stochasticity

Organisms are most affected by stochastic events and processes which occur on time scales which are shorter than the organism's life span [@ref]. Weekly heavy rains which alter a lake's salinity [@ref] are more likely to affect the lake's inhabitants than a multi-centennial drought, and high-salinity conditions may be perceived as the (stressful) standard by organisms which were born during periods of drought. However, stochastic processes and events which occur on time scales that are longer than an organism's lifespan may still cause significant effects on a population's fitness and stability. Droughts which occur on the time scale of centuries or millennia (@haig_assessment_2013) are unlikely to affect organisms directly, but such events could still alter the population's habitat or breeding grounds enough to cause a population collapse or prevent individuals from reproducing in their habitual breeding grounds (or reproduce altogether).

For an event or process to be recognized as deterministic by an individual, it must occur multiple times during the individual's lifetime (but the converse is not true). *some animals can develop memory* [@foley_severe_2008]

Trees that have drought resilience have higher mortality [@desoto_low_2020] *check the stats & causation*

# Methods

<!-- - look at HPAMs? -->

Inform priors and simulation distributions using Indigenous Traditional Knowledge

# Movement simulations



# Evnironmental stochasticity map

- currently don't have a raster of stochasticity => paper / product
- PCA on main drivers/causes of stochasticity

# Movement analysis

- add HFI to analysis

# Synthesis chapter
<!-- why is this  work important? so what? now what?-->

\newpage

# References
