\clearpage

# Introduction

## TODO:

15-20 pages double spaced:

- situate the thesis within the field
- movement changing as a response to environmental stochasticity
- Ideal Free Distribution and how it's changed over time: when does it not work and when does need to be modified?
- confusion between stochasticity and seasonality
- stochasticity affects many things, but focusing on movement because it's easier to track and understand
- move all info from "current knowledge" to intro
- add appendix B (resources as random variables) from the movement ecology paper to intro; add some concrete examples to explain within the context of ecology
- define all terms clearly
- add all material on scale (not present in chaper 1)

chapters:
- the ME chapter can become chapter 1 as is
- chapter 3:
..- use already calculated HR estimates and UDs (Mike to send data soon)
..- predict long-term raster from N/S america model to fit models
..- write and complete since it's easy
- chapter 4: mike writing some edits, then can add directly as is
- intro: look at chapter 1 from MSc thesis (see above and `C:\Users\stefa\Documents\GitHub\hr-environ-stoch-phd\writing\proposal\msc-proposal\mezzini-stefano-msc-proposal.pdf`)
- write summary chapter (~ synth all findings in context of the field at the end of the intro)
- chapter 2: write in terms of North and South America; keep fitting in background

## text

Movement allows animals to respond rapidly and continuously to a wide variety of stimuli from the external environment and within their body [@nathan_movement_2008].
Animals may move to escape predators or avoid competitors but also search for resources (e.g., food, water, heat, a new den or nesting spot), a mate, or a new group, and defend such resources and conspecifics.

Within the last two centuries, widespread changes in climate [@ipcc_climate_2023] and increases in anthropogenic activity [@tucker_moving_2018] have had profound effects on species' movement behavior and their ability to adapt to and respond to change [@diffenbaugh_changes_2013; @woo-durand_increasing_2020; @sih_evolution_2011; @hirt_environmental_2021].
Consequently, many researchers have studied species' ability to respond to change in the short term [@southwood_habitat_1977], the long term [@levins_evolution_1974], and the when changes are too severe to respond to [@botero_evolutionary_2015].
In particular, the field of movement ecology has focused on animals' responses to change trough movement [@nathan_movement_2008] while formalizing core theory presented by previous foundational work [e.g., @burt_territoriality_1943; @southwood_habitat_1977].
Most of the work addresses animals' responses to changes in mean conditions, although some work has addressed animals' responses to stochastic (i.e., unpredictable) change [@lande_risks_1993; @bull_metapopulation_2007; @fung_quantifying_2018].

Despite having received limited attention within ecology and conservation [@marcus_changing_2023], environmental stochasticity can have substantial impacts on an ecosystem's stability [@ref] and energetic balance [@ref]. 

In this thesis, ***I extend the work on the effects of stochasticity*** on four projects, each in a separate chapter.
The first three chapters focus on quantifying environmental stochasticity and species' (mainly mammals') response to changes in resource abundance and unpredictability, while the fourth chapter illustrates addresses the effects of air temperature on mammals' movement rates and habitat selection.
In Chapter 1, I illustrate how animals' spatial needs depend on both the abundance and unpredictability of resources through simulations.
I demonstrate that both variables have nonlinear effects on animals' range sizes, and I provide a case study illustrating how the concepts can be applied to real-world telemetry data on a lowland tapir (*Tapirus terrestris*) from the Brazilian Cerrado [@medici_movement_2022].
In Chapter 2, I produce a model for quantifying mean and variance in NDVI from 1981 to 2025 throughout the Nearctic and Palearctic.
In Chapter 3, I leverage the estimates produced in Chapter 2 as proxies of resource abundance and stochasticity to test the hypotheses presented in chapter 1 using telemetry data on ***XXX*** individuals across ***XXX*** species throughout the Nearctic and Palearctic.
In Chapter 4, I quantify the effects of air temperature on the movement rates and habitat selection of six species of mammals within the north-western Nearctic.
Finally, in Chapter 5, I summarize the work I presented in this thesis and I demonstrate its significance within the larger picture of movement ecology, conservation, and quantitative zoology.

I wrote each chapter in this thesis as a standalone publication, so the following chapters do not assume readers are familiar with any previous chapters nor this introduction.
Additionally, the chapters occasionally use the plural first person ("we") as as common practice with scientific papers with more than one author.
While each chapter is designed to address each objective independently, together they provide convergent evidence towards the role of stochasticity and change in shaping animal movement behavior.
**Appendix 1** contains details on published works I made substantial contributions to during the course of my doctorate.
