\newpage

\newcommand*\e{\mathbb E} <!-- expectation (blackboard bold) E -->

\newcommand*\var{\mathbb V} <!-- variance (blackboard bold) V -->

# Chapter 1: Literature review and quantitative simulations {#review-and-sims}

\noindent The amount of resources an organism is able to access is a strong determinant of its odds of survival and reproduction. Resource limitations can cause individuals to experience a negative energetic balance, which can then result in lower fitness [@hou_cold_2020; @le_bot_fishery_2019], changes to community structure [@haney_tipping_2018; @burson_competition_2018; @riotte-lambert_environmental_2020; @ghislandi_resource_2018], altered physiology [@dai_pra_ground_2022; @rocha_life_2021; @le_bot_fishery_2019; @wessling_seasonal_2018], lower chance of reproduction [@stefanescu_timing_2021; @schmidt_interplay_2020; @le_bot_fishery_2019; @douglas_relative_2014], and even death [@foley_severe_2008; @berger_climate_2018]. Thus, many organisms will adapt their behaviors in response to changes in local resource abundance to ensure their needs are met. Some species may respond to fluctuations in resource abundance by, if possible, switching to other food sources [@steinmetz_effects_2021; @le_bot_fishery_2019], reducing energetic costs by reducing body heat [@schmidt_interplay_2020], or entering hibernation or torpor [@fjelldal_nightly_2021; @mohr_cellular_2020; @boyles_optimal_2020], but movement represents one of the most readily available traits that species can adjust, whether this be by modifying their home range [@bista_effect_2022; @bradsworth_using_2022; @lucherini_habitat_1996; @relyea_home_2000; @yu_artificial_2022; @arechavala-lopez_common_2019], migrating [@middleton_green-wave_2018; @geremia_migrating_2019], dispersing [framework: @southwood_habitat_1977; amphibians: @cayuela_determinants_2020; birds: @pretorius_movement_2020; @wheat_migrate_2017; mammals: @singh_migration_2012], or moving nomadically [@teitelbaum_beyond_2019; @nandintsetseg_variability_2019].

The relationship between animal movement and resource abundance has been of interest to biologists for over half a century. @burt_territoriality_1943 considered the search for food as the primary driver for animal movement within an animal's home range. Three decades after, @southwood_habitat_1977 suggested that change in resource abundance is a strong determinant of how animals decide where to live and when to reproduce. Two years later, @harestad_home_1979 proposed that the simplest relationship between resource abundance and an animal's home-range size is

\begin{equation}
H = C / R,
(\#eq:harestad-eq)
\end{equation}

\noindent where $H$ is the animal's **home-range size**, $C$ is the animal's resource consumption, and $R$ is the **resources** an animal can access. Harestad and Bunnel's model is simple to conceptualize and allows for testable predictions, but a species' spatial requirements likely depend on numerous other factors, such as competition, metabolic rate, diet, and body weight [@harvey_primate_1981; @lindstedt_home_1986; @reiss_scaling_1988; @harvey_primate_1981; @gittleman_carnivore_1982; @jetz_scaling_2004; @boratynski_energetic_2020; @noonan_effects_2020]. While many researchers have since demonstrated that animals adapt their home ranges in response to resources abundance, few studies build upon others' previous work. Instead, results are reported as independent, *de-novo* findings. Consequently, we currently lack a unifying framework for quantifying the effects of resource abundance on animals' spatial needs. In addition, while much work has been done on estimating animals' responses to average resource abundance, there is little to no information on how they respond to unpredictable changes in resources.

In this paper, we refer to a location's average amount of resources as **resource abundance**, while use the phrase **resource stochasticity** to indicate the variability in resource abundance due to unpredictable causes. We argue that, on its own, a habitat's long-term resource abundance is not sufficient to assess the habitat's quality, nor make predictions about how much space an animal might use. For instance, a grassland with relatively low but constant forage availability will clearly require drastically different behaviors and adaptations from a desert location with equally scarce forage but rare, sudden, and strong pulses of resources. In the first scenario, an animal may require a large but constant home range as it moves between locations in search of food [*sensu* @teitelbaum_beyond_2019], while an animal in the second scenario may switch between dispersal as it searches for high-resource patches and short-term range residency until the local resources are depleted. Although it may be possible for both habitats to have the same long-term average resource abundance, the differences in resource unpredictability result in substantially different movement strategies and life histories being selected for. Although it is generally expected that resource unpredictability will decrease animals' fitness and a landscape's energetic balance [@chevin_adaptation_2010], there is little empirical evidence to support this hypothesis [but see: @herfindal_prey_2005; @nilsen_can_2005; @rizzuto_forage_2021].

## Thesis structure and aims

\noindent This thesis aims to quantify how animal's movement and use of space are affected by environmental stochasticity, with a focus on resource stochasticity. This work has four key objectives: (i) estimating individuals' spatial requirements in a way which is insensitive to variation in sampling protocols and data quality; (ii) quantifying resource stochasticity; (iii) estimating the effects of resource stochasticity on mammalsworldwide using models that are robust to commonly-found issues (e.g., correlations within species); and (iv) understanding changes in weather and climate affect mammal movement within BC. The present section provides the structure for this thesis, where each chapter is structured as a stand-alone body of work to be submitted for publication. While each chapter is designed to address each objective independently, together the chapters provide convergent evidence towards the role of stochasticity and change in shaping animal space use.

In this chapter, I will illustrate how animals' spatial needs depend on both the abundance and unpredictability of resources. First, I will set the theoretical background necessary for the successive sections by introducing key concepts and notation. Next, I will provide a review of the effects of resource *abundance* on animals' spatial needs while suggesting a unifying hypothesis. Afterwards, I will provide a review of the effects of resource *stochasticity* on animals spatial needs while suggesting a second unifying hypothesis. Subsequently, I will demonstrate the power of these two hypotheses using quantitative, simulated responses to changes in resource abundance and unpredictability. Finally, I will demonstrate how this framework can be used in practice to describe the movement ecology of a lowland tapir (*Tapirus terrestris*) from the Brazilian Cerrado [@medici_movement_2022]. Results from the simulations and empirical example will be presented using a fully transparent approach that will allow researchers to replicate the work and apply the methods to their own tracking data.

In **Chapter \@ref(var-raster)**, I will produce a global raster of a new resource stochasticity index. This metric will then serve as the basis for my subsequent investigation into the relationship between resource stochasticity and animal movement.

**Chapter \@ref(movement-ch)** will use an unprecedented and conservation-relevant animal tracking dataset (>3000 animals from 87 globally-distributed species) to investigate how mammals' spatial needs change with environmental variance.

**Chapter \@ref(bc-cc)** will estimate how changes in BC's climate over the next century will affect where, how, when, and how much mammals in BC will move.

Finally, **Chapter \@ref(synthesis)** will summarize the work presented in this thesis and demonstrates its significance within the larger picture of movement ecology, conservation, and quantitative zoology.

Chapters \@ref(os)-\@ref(timeline) contain various supporting information, namely links to the code and data used in this thesis (**Chapter \@ref(os)**), a table of all abbreviations used in the thesis (**Chapter \@ref(abbreviations)**), a table of all mathematical notations and symbols used in the thesis (**Chapter \@ref(symbols)**), and the tentative timeline (**Chapter \@ref(timeline)**, which will not be present in the final version of the thesis). **Appendix 1** contains details on published works I made substantial contributions to. 
