\newpage

# Chapter 3: Movement analyses {#movement-ch}

\noindent This chapter will test the hypotheses presented in chapter \@ref(review-and-sims) using the estiamted resource abundance and stochasticity from chapter \@ref(var-raster) and a worldwide mammal tracking dataset with over 3,000 individuals across more than 85 species. The tacking data will be modeled using continous-time movement models (CTMMs) via the `ctmm` package [@fleming_ctmm_2021] for `R` [@r_core_team_r_2022]. Each of the movement models will then be used to estimate the animals' spatial needs via their Utilization Distributions (UDs) estimated via Autocorrelated Kernel Density Estimation [AKDE, see @silva_autocorrelationinformed_2022; @noonan_comprehensive_2019]. The effects of resource abundance and stochasticity will then be quantified using the estimates of $\e(R)$ and $\var(R)$ from the previous chapter and a Hierarchical Generalized Additive Model [HGAM, see @pedersen_hierarchical_2019] fit via the `mgcv` package [@wood_generalized_2017] for `R`. The HGAM will estimate effects of $\e(R)$ and $\var(R)$ on the mammals' spatial needs while accounting for differences in the animals' body size [@noonan_effects_2020], diet type, and taxonomy. Additional analyses will also be performed to test whether the animals' range crossing time, long-term average speed, daily speed, and directional persistence also depend on $\e(R)$ and $\var(R)$.

Results from the HGAMs will allow researchers and conservation managers to predict mammals' spatial needs and movement via quantitative environmental variables ($\e(R)$ and $\var(R)$) and known traits (i.e., body size, taxonomy, and diet type). Consequently, the models will have the potential of predicting animals' spatial needs without any tracking data, which is of particular importance for animals which are hard to track and study, whether this be due to their small mass (e.g., rodents), their scarce numbers, their elusiveness, or ethical concerns.
