\newpage

# Chapter 4: Effects of climate change on BC mammals {#bc-cc}

\noindent This chapter will provide a BC-focused analysis on the effects of weather and climate on mammal movement. Using more than a decade of pre-collected telemetry data on 5 species of terrestrial BC mammals (caribou, cougars, elk, grizzly bears, and mountain goats), I will estimate how mammalian movement ecology responded to historical weather conditions and predict how and mammalian movement will respond under different climate change scenarios in the current century. More specifically, I will determine how changes in temperature and precipitation will affect when, how, how much, and where BC mammals move over the next 80 years (see sections below). Additionally, in collaboration with Dayna Weststrate and Aimee Chhen (current students from the Quantitative Ecology Lab), I will produce quantitative and data-informed estimates of how climate change will shape Human Wildlife Conflict in BC’s protected areas. A preprint on the work is available at https://doi.org/10.1101/2023.07.11.548618.

## Weather and climate data

Short-term historical weather data will be estimated using hourly projections from the ERA5-Land dataset [@copernicus_climate_change_service_era5-land_2019] downloaded via the `ecmwfr` package [@hufkens_ecwmfr_2019] for `R`. While real-time measurements would provide more accurate estimates, the tracked animals were not sufficiently close to a weather station throughout the tracking period. Some of the elk datasets included collar measurements of air temperature, but such measurements are likely biased by solar radiation and the animals' body heat. Therefore, including such temperature data would result in species-level biases in the HGAM.

The climate data during the current century will be estimated using the latest Shared Socioeconomic Pathway (SSP) predictions by the IPCC [@riahi_shared_2017], which will be downloaded via the `climatenaR` package [@burnett_climatenar_2023] for `R`. Since the SSPs only provide predictions for average monthly precipitation and average, maximum, and minimum montly temperatures, the predictions will likely fail to account for the heterogeneity within months and the effect of sub-monthly extreme weather, such as heat waves which last a week or less. If the movement models suggest highly heterogeneous and nonlinear responses to temperature or precipitation, it may be necessary to simulate daily fluctuations in weather.s

## Determining when, how, and how much mammals move

The movement of each of the mammals in the dataset will be modeled using CTMMs via the `ctmm` package [@fleming_ctmm_2021] for `R`. Rather than imposing a model on the tracking data, the model will be determined based on a model selection process that accounts for the data's sampling frequency [@noonan_scale-insensitive_2019]. Next, I will use the subset of models with speed estimates and their associated data to estimate animals' instantaneous movement rates between known locations. Since CTMMs always predict a non-zero speed, movement rates will be standardized by subtracting the minimum speed, which will be assumed to be approximately equal to zero.

Finally, the chance that an animal will move and the animal's speed (given that it is moving) will be modeled using an HGAM with a hurdle Gamma distribution via the `brms` package [@burkner_brms_2017; @burkner_advanced_2018] for `R`. The model will account for each species' changes in behavior throughout the day and throughout the year while also accounting for the effects of temperature and precipitation, as well as how the species' daily and seasonal trends are affected by changes in temperature and precipitation. While snow depth is also an important determinant of mammal movement [e.g., @pedersen_quantifying_2021; @melin_effect_2023], I will not include it in the analysis because I am unaware of any predictions of snow depth in future decades.

## Determining where mammals will move

I will estimate the mammals' spatial selection using Hierarchical Resource Slection Functions (HRSFs). To avoid the common limitations of linear or polynomial feature selection which many RSFs suffer from, I will fit the HRSFs as Heterogeneous Poisson Processes (HPPPs) using HGAMs via the `mgcv` package [@aarts_estimating_2008]. This will allow me to estimate common, nonlinear preferences between animals from the same species. However, since HPPPs require a large number of quadrature points (i.e., locations where the animal was \emph{not}) relative to the number of GPS locations (i.e., $\gtrapprox 200$), the computational requirements will likely be too high to fit a single hierarchical model for all mammal species in the dataset. However, this is not a serious issue, since the models can still be used independently at the species level, and a mammal-level estimate from an opportunistic sample of 5 species would likely be biased and lead to questionable predictions.

The HRSFs will account for animals' preference for three resources: forest cover, water, and elevation, which will be estimated using temporally static rasters of forest cover, distance to nearest freshwater body, and elevation. While temporally dynamic rasters would provide more accurate estimates (e.g., by accounting for deforestation and droughts), I am unaware of any such estimates. In addition, the models will also estimate how temperature and precipitation affect the species' prefence for each of the resources. Each of the model terms will be estimated using sufficiently flexible yet reasonably constrained smooths. To decrease computation time (with no cost to accuracy), the models will be fit using the `bam()` function from the `mgcv` package with fast residual maximum likelihood and a discretization of covariates [@wood_generalized_2017-1; @li_faster_2020]. The models and predictions produced by this chapter will be tailored specifically to the needs of conservation organizations within BC, including BC Parks, which whom I have been collaborating through a Living Labs project.
